### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rkarlsba**
Added a line of info about why the channel can't be configured.

### CODE REVIEW

**Comment by martin-ger** [comment]
Looks that you have removed 346 lines of the Readme...

**Comment by rkarlsba** [comment]
oops… I'll take a look - I'm on a satellite link now, some something may have gone wrong :) 

Vennlig hilsen 

roy 
-- 
Roy Sigurd Karlsbakk 
(+47) 98013356 
http://blogg.karlsbakk.net/ 
GPG Public key: http://karlsbakk.net/roysigurdkarlsbakk.pubkey.txt 
-- 
Hið góða skaltu í stein höggva, hið illa í snjó rita.

**Comment by rkarlsba** [comment]
You're right - can you please remove this pull request? I only added one line - I can make a new pr

**Comment by rkarlsba** [comment]
Branch deleted

**Pull request closed without merging**
