### PR TITLE
Added GPIO command line support

### PR DESCRIPTION
**Pull request by robnewton**
Be warned, I haven't tested this yet (on Windows right now) but I wanted to get this out there in hopes it could find it's way into your next compiled bins. I'll follow up when I get a chance to configure the compile environment on a Mac.

### CODE REVIEW

**Comment by martin-ger** [comment]
I like the idea. Thank you! Will integrate it soon.

What I think is still missing, is a command to read the inputs? Also, I understand why you did a reformat of the file, but this makes it hard to read diffs from older versions.

**Comment by robnewton** [comment]
Yeah that second commit was an attempt to undo the the formatting the IDE was doing. I'll fix it and add the read of inputs today. Good catch.
________________________________

**Comment by robnewton** [comment]
Added a get action which will read a pins value and return it to the command line as the response. The indents should be clean as well, but let me know if you don't see it fixed.

Ex usage:
`gpio 2 get`

**Comment by martin-ger** [comment]
Sorry, doesn't compile like it is: variables not defined and string compares in C are done with strcmp(). Also logic flaw with the nTokens.

**Comment by robnewton** [comment]
I figured it would have some syntax issues since I don't have the toolchain setup. Am I right to assume that by closing this, you do not intend to pull it in?

**Comment by robnewton** [comment]
Fixed the issues. Still working on getting the toolchain up and running (will try Ubuntu Docker next since OSX is no longer supported. I'll just do another pull once it's compiling.

**Pull request closed without merging**
