### PR TITLE
Enhancements

### PR DESCRIPTION
**Pull request by xxxajk**
Remove execute permissions from source files
Add sub-make to build lwip ensuring it is not out of date and contains sane options.
Force add XTENSA_TOOLS_ROOT to search path in Makefile.
Add some useful targets in Makefile.
Add DHCP server support on ENC28J60.
Remove all out of date and unused files.
Add Symlink to lwip netif include directory.
Remove outdated lwip include directory and replace it with a symlink to reduce source bloat.

TO-DO: Remove need for symlinks and just point to the header directories instead by using a variable in the Makefile.

NOTE: Assumes dependencies are installed in the parent directory of the source, including libraries and build tools.

### CODE REVIEW

**Comment by martin-ger** [comment]
Thanks a lot for your contributions!

I am currently trying to test the changes. Let me ask two questions:
- How exactly is your directory structure? (I have ./esp-open-skd/esp-open-lwip and ./esp_wifi_repeater on the same level. Minor problem - think, I got it compiled)
- Does it boot you ENC correctly - for me it always got stuck after "Staring enc"? Do you use the wiring as given in my Readme?

Thanks again,
Martin

**Comment by xxxajk** [comment]
Ok, for whatever reason, isr isn't being hit by the eth.
Further testing is showing that some registers are not being written to.

**Comment by xxxajk** [comment]
Oh and just FYI, the same hardware under Arduino _does_ work with my modified EtherCard library.

**Comment by martin-ger** [comment]
For my tests I applied both patches to lwip and the repeater.

> Further testing is showing that some registers are not being written to.
Does this mean, there are some additional code changes neccessary?

**Comment by martin-ger** [comment]
Integrated the two pull request. Thanks for all the improvements in details. I reverted it back to the self-contained compile with the included lwip-lib. I understand that a symlink is better for consistency, but I assume, that the complete build environment might be too complex for someone, who just want's to change options and recompile.

**Comment by xxxajk** [comment]
cool, whatever you need.

**Pull request merged**
