### PR TITLE
GPIO support tested and working on ESP-12F

### PR DESCRIPTION
**Pull request by robnewton**
All syntax issues from the pseudo code first attempt have been resolved. The code compiles and I have flashed an ESP-12F testing with controlling GPIO04 as input and output setting the output to high and low repeatedly with success. I have not yet tested from the web interface, but I don't see any reason that shouldn't work considering how the web interface just patches into the command_line functions. I'll test it out tomorrow night specifically though.

### CODE REVIEW

**Comment by Budman1758** [comment]
I'm curious if you have a specific use case in mind for this or if its just a general feature to extend this software's functionality? (which IMHO is a good thing :> )

**Comment by robnewton** [comment]
Guilty as charged. I am solving a problem but figured it would be easy enough to contribute it back rather than doing this in private only.

**Comment by robnewton** [comment]
Any specific requests while I'm in there?

**Comment by Budman1758** [comment]
> Any specific requests while I'm in there?

No, not really.  Was just curious if you had something special cooking.
I can see lots of uses for GPIO control for stuff.  Will all usable GPIO be available?

**Comment by robnewton** [comment]
Nothing special cooking really. I'm using the GPIO support to control opening a closing a low current circuit with a transistor. I am triggering this over HTTP from a mobile device using this repeater to blend what would be two networks together into a single AP for the device. Using the ESP to control the transistor is really just a convenience thing since the chip was already there and has GPIO.

The code in the PR allows for getting or setting pins numbered 0-16.

**Comment by martin-ger** [comment]
Some minor changes:
- Added to README.md
- Pinmodes saved persistent in config with "save"
- Added mode _in_pullup_

Thanks for your ideas and the contribution!

**Comment by robnewton** [comment]
Great idea about the pinmode saves!

**Pull request merged**
