### PR TITLE
OTA (Over the air) update support

### PR DESCRIPTION
**Pull request by christianchristensen**
This patch needs some work on the build side to match up with the current instructions in the README; mostly what files are output in the firmware directory as well as the memory addresses to flash. However, these allow for the device to request an updated bin file and switch between the two.

### CODE REVIEW

**Comment by christianchristensen** [comment]
Example session snippet from serial console:

```
CMD>help
show [config|stats|route|dhcp|acl|mqtt|ota]
...
ota [switch|update]
CMD>show ota
Firmware update: 192.168.1.53/rom1.bin
Currently running rom 0.
CMD>ota update
Updating...
Update initiated
...
Booting rom 1.
CMD>show ota
Currently running rom 1.
CMD>ota switch
Swapping from rom 1 to rom 0.
Restarting...
ROM switched
CMD>show ota
Currently running rom 0.
```

**Comment by christianchristensen** [comment]
related: https://github.com/martin-ger/esp_wifi_repeater/issues/41

**Comment by alonewolfx2** [comment]
@christianchristensen i tried your branch but i cant update it. it seems it cant resolve dns when using http server, also i tried tftp but nut luck. what is your server for serving ota files?

**Comment by martin-ger** [comment]
Add it to the main branch. Updated Readme.md, a little bit of the Makefile (to build both binaries on each change) and add variable ota_host and ota_port - however: currently the update itself fails for me with a SimpleHTTPServer on LInux as the HTTP stream isn't processed correcly (the ESP sends a FIN after three data packets from the server) - will look into that later...

Thanks again for your work!!

**Comment by christianchristensen** [comment]
@martin-ger It failed for me using python SimpleHTTPServer as well. I ended up just uploading to a hosting provider (best guess nginx or apache) and the ota request to the URL functioned fine and the updated version was put in place. I haven't looked deeply, but perhaps related to https://github.com/raburton/rboot-sample/issues/6 ?

@alonewolfx2 are you able to use ping or an IP address directly? This is performing an HTTP request, so I would not expect tftp to work (https://github.com/martin-ger/esp_wifi_repeater/blob/872bc29e57c986ec85cfaa6eda666f5a3c88209c/user/rboot-ota.c#L190-L193)

**Comment by christianchristensen** [comment]
Thanks for integrating and updating @martin-ger and also thank you for the fabulous work on this - it's been a delight to setup and use!

**Comment by martin-ger** [comment]
Okay, found it: the SimpleHTTPServer sends the HTTP reply in two packets: First the response code, then the other attributes - the old loaded expected it in one packet. Now it works at least with the SimpleHTTPServer (and hopefully with all others - as long as they don't scatter the response even further...)

**Pull request merged**
